version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "8082:8082"
    command: npm start
  my-mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    command: mongod
volumes:
  mongodb_data: